### ISSUE TITLE
Incorrect edge-case handling in Facade.endIdForVest()

### ISSUE THREAD

**Issue by fiddlemath** [reserve-protocol/protocol#375]
From the Solidified audit, item 17, the `<` in the following line should be a `<=`.

https://github.com/reserve-protocol/protocol/blob/946d9b101dd77275c6cbfe0bfe9457927bd221a9/contracts/facade/Facade.sol#L259

**Comment by tbrent** [comment]
Should first write a regression test that fails, then fix, then see test pass
