### ISSUE TITLE
Build fails on ubuntu 22.04, node v16.16.0

### ISSUE THREAD

**Issue by AndreiD** [reserve-protocol/protocol#456]
Used on: 

**Linux me-desktop 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Node v16.16.0**

Git clone this repo, npm install

~~~~
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: reserve-protocol@1.0.0
npm ERR! Found: dotenv@10.0.0
npm ERR! node_modules/dotenv
npm ERR!   dev dotenv@"^10.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer dotenv@"^16.0.1" from @withtally/tally-publish-dao@0.0.5
npm ERR! node_modules/@withtally/tally-publish-dao
npm ERR!   dev @withtally/tally-publish-dao@"^0.0.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/me/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/me/.npm/_logs/2022-11-07T10_36_55_322Z-debug-0.log
~~~~

tried with yarn install

<pre><font color="#A6E22E"><b>➜  </b></font><font color="#A1EFE4"><b>protocol</b></font> <font color="#66D9EF"><b>git:(</b></font><font color="#F92672"><b>master</b></font><font color="#66D9EF"><b>)</b></font> yarn install
<font color="#66D9EF">➤</font> <font color="#75715E">YN0000</font>: ┌ Resolution step
<font color="#F4BF75">➤</font> YN0002: │ <font color="#D7875F">reserve-protocol</font><font color="#87AFFF">@workspace:.</font> doesn&apos;t provide <font color="#D75F00">@ethersproject/</font><font color="#D7875F">abi</font> (<font color="#87AFFF">p537ba</font>), requested by <font color="#D75F00">@typechain/</font><font color="#D7875F">ethers-v5</font>
<font color="#F4BF75">➤</font> YN0002: │ <font color="#D7875F">reserve-protocol</font><font color="#87AFFF">@workspace:.</font> doesn&apos;t provide <font color="#D75F00">@ethersproject/</font><font color="#D7875F">bytes</font> (<font color="#87AFFF">pcf58c</font>), requested by <font color="#D75F00">@typechain/</font><font color="#D7875F">ethers-v5</font>
<font color="#F4BF75">➤</font> YN0002: │ <font color="#D7875F">reserve-protocol</font><font color="#87AFFF">@workspace:.</font> doesn&apos;t provide <font color="#D75F00">@ethersproject/</font><font color="#D7875F">providers</font> (<font color="#87AFFF">pe8ad9</font>), requested by <font color="#D75F00">@typechain/</font><font color="#D7875F">ethers-v5</font>
<font color="#F4BF75">➤</font> YN0060: │ <font color="#D7875F">reserve-protocol</font><font color="#87AFFF">@workspace:.</font> provides <font color="#D7875F">dotenv</font> (<font color="#87AFFF">p30487</font>) with version <font color="#87AFFF">10.0.0</font>, which doesn&apos;t satisfy what <font color="#D75F00">@withtally/</font><font color="#D7875F">tally-publish-dao</font> requests
<font color="#F4BF75">➤</font> YN0060: │ <font color="#D7875F">reserve-protocol</font><font color="#87AFFF">@workspace:.</font> provides <font color="#D7875F">eslint</font> (<font color="#87AFFF">pfefd3</font>) with version <font color="#87AFFF">8.19.0</font>, which doesn&apos;t satisfy what <font color="#D7875F">eslint-config-standard</font> requests
<font color="#F4BF75">➤</font> YN0060: │ <font color="#D7875F">reserve-protocol</font><font color="#87AFFF">@workspace:.</font> provides <font color="#D7875F">eslint-plugin-promise</font> (<font color="#87AFFF">p68544</font>) with version <font color="#87AFFF">6.0.0</font>, which doesn&apos;t satisfy what <font color="#D7875F">eslint-config-standard</font> requests
<font color="#F4BF75">➤</font> YN0002: │ <font color="#D7875F">reserve-protocol</font><font color="#87AFFF">@workspace:.</font> doesn&apos;t provide <font color="#D7875F">lodash</font> (<font color="#87AFFF">pc563a</font>), requested by <font color="#D75F00">@typechain/</font><font color="#D7875F">hardhat</font>
<font color="#F4BF75">➤</font> YN0002: │ <font color="#D7875F">reserve-protocol</font><font color="#87AFFF">@workspace:.</font> doesn&apos;t provide <font color="#D7875F">query-string</font> (<font color="#87AFFF">p64ac0</font>), requested by <font color="#D75F00">@withtally/</font><font color="#D7875F">tally-publish-dao</font>
<font color="#F4BF75">➤</font> YN0060: │ <font color="#D7875F">reserve-protocol</font><font color="#87AFFF">@workspace:.</font> provides <font color="#D7875F">wretch</font> (<font color="#87AFFF">p082dd</font>) with version <font color="#87AFFF">2.0.4</font>, which doesn&apos;t satisfy what <font color="#D75F00">@withtally/</font><font color="#D7875F">tally-publish-dao</font> requests
<font color="#F4BF75">➤</font> YN0002: │ <font color="#D7875F">typechain</font><font color="#87AFFF">@npm:3.0.0</font> doesn&apos;t provide <font color="#D7875F">typescript</font> (<font color="#87AFFF">p4ba7f</font>), requested by <font color="#D7875F">ts-essentials</font>
<font color="#F4BF75">➤</font> YN0000: │ Some peer dependencies are incorrectly met; run <font color="#87AFFF">yarn explain peer-requirements &lt;hash&gt;</font> for details, where <font color="#87AFFF">&lt;hash&gt;</font> is the six-letter p-prefixed code
<font color="#66D9EF">➤</font> <font color="#75715E">YN0000</font>: └ Completed
<font color="#66D9EF">➤</font> <font color="#75715E">YN0000</font>: ┌ Fetch step
<font color="#66D9EF">➤</font> YN0013: │ <font color="#D7875F">yargs</font><font color="#87AFFF">@npm:16.2.0</font> can&apos;t be found in the cache and will be fetched from the remote registry
<font color="#66D9EF">➤</font> YN0013: │ <font color="#D7875F">yargs</font><font color="#87AFFF">@npm:17.5.1</font> can&apos;t be found in the cache and will be fetched from the remote registry
<font color="#66D9EF">➤</font> YN0013: │ <font color="#D7875F">yargs</font><font color="#87AFFF">@npm:4.8.1</font> can&apos;t be found in the cache and will be fetched from the remote registry
<font color="#66D9EF">➤</font> YN0013: │ <font color="#D7875F">yn</font><font color="#87AFFF">@npm:3.1.1</font> can&apos;t be found in the cache and will be fetched from the remote registry
<font color="#66D9EF">➤</font> YN0013: │ <font color="#D7875F">yocto-queue</font><font color="#87AFFF">@npm:0.1.0</font> can&apos;t be found in the cache and will be fetched from the remote registry
<font color="#F4BF75">➤</font> YN0066: │ <font color="#D7875F">typescript</font><font color="#87AFFF">@patch:typescript@npm%3A4.7.4#~builtin&lt;compat/typescript&gt;::version=4.7.4&amp;hash=ddd1e8</font>: Cannot apply hunk #2
<font color="#F92672">➤</font> YN0018: │ <font color="#D7875F">ethereumjs-abi</font><font color="#87AFFF">@https://github.com/ethereumjs/ethereumjs-abi.git#commit=ee3994657fa7a427238e6ba92a84d0b529bbcde0</font>: The remote archive doesn&apos;t match the expected checksum
<font color="#66D9EF">➤</font> <font color="#75715E">YN0000</font>: └ Completed in 20s 652ms
<font color="#F92672">➤</font> YN0000: Failed with errors in 20s 774ms</pre>

**Comment by AndreiD** [comment]
fixed by updating dotenv to latest. should I do a push request or ...?

**Comment by tbrent** [comment]
Actually: @AndreiD if you could confirm `master` builds for you on ubuntu, I'll go ahead and close this issue. Thanks
