### ISSUE TITLE
Not all integration tests will work starting from the same fork block

### ISSUE THREAD

**Issue by tbrent** [reserve-protocol/protocol#502]
People developing collateral plugins sometimes are building on top of projects that were not deployed until after our canonical (Aave-driven) fork block. We either need to use a block number that works for everyone (the latest seems like the only schelling point here) or we need to support different fork block numbers per test.

**Comment by julianmrodri** [comment]
Block numbers can be defined in `test/integration/fork-block-numbers.ts` and then you can set it up at the beginning of the test with `await setup(forkBlockNumber['aave-compound-rewards'])` (for example). Only issue is its not working in CI but locally should work.

**Comment by julianmrodri** [comment]
The only issue we have is that the `fixture` currently only supports form our default block forward, but not prior ones. Already opened an issue for this to get fixed but priority is low I think.

**Comment by tbrent** [comment]
Oh this is excellent! I'll point hackathon people towards this

**Comment by julianmrodri** [comment]
Yeah this performs a hardhat network reset, on the fly.. for some reason it breaks in CI. Already opened an issue with HH but I dont expect any solution. So as long as it works locally I think its ok for them to use any block number using that helper `setup` function

**Comment by tbrent** [comment]
Closing this since we have a solution now
