### ISSUE TITLE
SLOW TradingExtremes tests are unused

### ISSUE THREAD

**Issue by tbrent** [reserve-protocol/protocol#549]

**Comment by julianmrodri** [comment]
Extreme tests in `Rtoken.test.ts` do not work when running `SLOW=true`. There seems to be like it was not updated for a while. Fixing the way the Collateral is created is not enough. Needs advanced debugging.

**Comment by julianmrodri** [comment]
* ZZStRSR tests seem to be OK when running in SLOW mode
* ZTradingExtreme tests are not. They also have bunch of failures.

**Comment by tbrent** [comment]
@julianmrodri that's right, closing
