### ISSUE TITLE
Add Custom Token to RToken as Collateral [Plugin Address Error]

### ISSUE THREAD

**Issue by j0xhn** [reserve-protocol/protocol#570]
Learning about your project, very cool.  It was mentioned that like in "uniswap" one could add custom tokens to make their Rtoken.  Found the place I thought would be to do it in the UI:
<img width="463" alt="image" src="https://user-images.githubusercontent.com/2646310/213097651-98e154c4-8696-4983-81ab-350447599170.png">
then gives me this error though:
<img width="447" alt="image" src="https://user-images.githubusercontent.com/2646310/213098119-c830ab47-3daf-4018-ae59-3554a62977f9.png">

How does one get collateral approved? Does that make sense or any documentation on how to achieve what i'm looking to do: add a custom token to use in the pool of RToken creation?

**Comment by julianmrodri** [comment]
To add collateral to an RToken you first need to *create* a collateral plugin. This means coding a contract that follows some interface that we defined and should maintain some invariants which are critical to the system. So it is not a trivial step. So far we only have Production-ready plugins for Fiat coins (like DAI, USDC, USDT), WBTC, WETH,and Compound V2 and Aave V2. 

Its not adding the address of the token or getting it approved, its a more involved work which includes preparing the Plugin. Hope this helps.

You could create an issue requesting that specific plugin and we can discuss it.

**Comment by j0xhn** [comment]
thanks for the quick reply - how does one create a collateral plugin? Is there a template online that I could follow and be able to integrate my own real world asset backed tokens into your ecosystem for example, would love to mint tokens that are compliant with your ecosystem, like much about what you are working on and appreciate the advancements in this tech.  Are you familiar with SuperFluid and what they are doing with streaming tokens? Anyways, yeah the specific plug would be for tokens that denote either cash flows or revenue streams or that represent physical assets such as gold or real estate.

**Comment by tbrent** [comment]
Check out `docs/collateral.md`. It definitely requires the ability to write code and understand the inner workings of the defi protocol you are building on top of.
