### ISSUE TITLE
Convex stable metapools (with fraxbp + 3pool)

### ISSUE THREAD

**Issue by tmattimore** [reserve-protocol/protocol#685]
- [ ] MIM + 3CRV
- [ ] ALUSD+FRAXBP
- [ ] LUSD+FRAXBP
- [x] eUSD+FRAXBP

**Comment by tbrent** [comment]
eUSD/fraxBP in #733

**Comment by tbrent** [comment]
alUSD is blocked by not having an oracle. MIM or LUSD could go next.

**Comment by tmattimore** [comment]
Did MIM or LUSD get into this one?

**Comment by tbrent** [comment]
It is done...

**Comment by tmattimore** [comment]
taylor is a beast taylor is a beast taylor is a beast
