### ISSUE TITLE
Document the rollout plan for broker changes and how it impacts various products in our system

### ISSUE THREAD

**Issue by tmattimore** [reserve-protocol/protocol#717]
- [x] create a written plan for broker changes (what they are, how they impact the system, and proposed rollout plan)
- [x] how do future rtokens work?
- [x] how does upgrade itself get tested and rolled out for eUSD?

**Comment by julianmrodri** [comment]
* Prepared plan in Notion (shared offline)
* Once Register is updated all RTokens in the future will work with the fix in place
* We are building a Proposal simulator to confirm the eUSD proposal works as expected before doing the final execution.
