### ISSUE TITLE
RESEARCH: propose collateral plugin status backtester design

### ISSUE THREAD

**Issue by tmattimore** [reserve-protocol/protocol#741]
Idea: Deploy a colalteral plugin, let it hang out in hidden mainnet deployment. Check if things work by going block by block and checking.

Problem: Unsure how much reftok decreases (or if it decreases) for Convex plugins.

Output of this ticket: Proposed design for a system that allows us to do this and tighter estimate

**Comment by tmattimore** [comment]
could potentially be forward looking and avoid delay

**Comment by pmckelvy1** [comment]
started a document here https://www.notion.so/myreserve/Collateral-Plugin-Backtester-f585dae44f3348729b843301ff92da51
