### ISSUE TITLE
redeem at previous basket nonces

### ISSUE THREAD

**Issue by tmattimore** [reserve-protocol/protocol#795]
Can allow redeemer to redeem at any basket, even a previously defaulted one, as long as the redemption is prorata based on balances held by the BackingManager. Might even be able to do a linear combination of basket nonces. 

Requires changes to the BasketHandler's storage to track all previous baskets. 

To think about: How do reward balances that could be claimed factor in? Can you get more out of the system than you should be able to if reward balances have accumulated to one of the collateral tokens being swapped out, mid-rebalancing?

**Comment by julianmrodri** [comment]
Merged into 3.0.0
