### ISSUE TITLE
cache prices in Asset plugins

### ISSUE THREAD

**Issue by tmattimore** [reserve-protocol/protocol#806]
not urgent if we cache prices in RecollateralizationLib. That would leave the RTokenAsset price being the only duplicate calculation.

--

We have `refresh()`, so it's only natural.

RTokenAsset is the tricky part. Either we have to leave its `refresh()` empty and leave it inefficient, or special-case it to refresh _after_ all the other registered plugins have refreshed.

**Comment by tbrent** [comment]
We only call `price()` once for each asset now per protocol interaction, so this is unneeded now
